#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowModerniser.Data
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ExecuteFxExpression")]
	public partial class ExecuteFxExpressionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Context = "Context";
			public const string OutputParameters = "OutputParameters";
			public const string InputParameters = "InputParameters";
			public const string Expression = "Expression";
			public const string EntityLogicalName = "EntityLogicalName";
		}
		
		public const string ActionLogicalName = "ExecuteFxExpression";
		
		public string Context
		{
			get
			{
				if (this.Parameters.Contains("context"))
				{
					return ((string)(this.Parameters["context"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["context"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity OutputParameters
		{
			get
			{
				if (this.Parameters.Contains("outputparameters"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Parameters["outputparameters"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Parameters["outputparameters"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity InputParameters
		{
			get
			{
				if (this.Parameters.Contains("inputparameters"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Parameters["inputparameters"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Parameters["inputparameters"] = value;
			}
		}
		
		public string Expression
		{
			get
			{
				if (this.Parameters.Contains("expression"))
				{
					return ((string)(this.Parameters["expression"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["expression"] = value;
			}
		}
		
		public string[] EntityLogicalName
		{
			get
			{
				if (this.Parameters.Contains("entitylogicalname"))
				{
					return ((string[])(this.Parameters["entitylogicalname"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["entitylogicalname"] = value;
			}
		}
		
		public ExecuteFxExpressionRequest()
		{
			this.RequestName = "ExecuteFxExpression";
			this.Expression = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ExecuteFxExpression")]
	public partial class ExecuteFxExpressionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Out = "Out";
		}
		
		public const string ActionLogicalName = "ExecuteFxExpression";
		
		public ExecuteFxExpressionResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity Out
		{
			get
			{
				if (this.Results.Contains("out"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["out"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Results["Out"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
