<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.56" />
    <PackageReference Include="Microsoft.CrmSdk.Workflow" Version="9.0.2.56" />
    <PackageReference Include="UiPath.Workflow" Version="6.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Activities" />
  </ItemGroup>

</Project>
