name: CI BUILD

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Restore Packages
      run: nuget restore WorkflowModerniser.sln
    
    - name: Build solution
      run: msbuild WorkflowModerniser.sln -t:build -p:OutputPath=WorkflowModerniser\bin\Release -p:Configuration=Release

    - uses: vimtor/action-zip@v1.2
      with:
        files: WorkflowModerniser\bin\Release\
        dest: WorkflowModerniser.zip

    - uses: actions/upload-artifact@v4
      with:
        name: WorkflowModerniser
        path: WorkflowModerniser.zip
        
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: WorkflowModerniser.zip
